---
abstract: 'Convert MultiMarkdown syntax to (X)HTML'
author:
  - 'Tomas Doran <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  List::MoreUtils: 0
  Test::Exception: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MultiMarkdown
no_index:
  directory:
    - inc
    - t
requires:
  Digest::MD5: 0
  Encode: 0
  Text::Markdown: 1.0.26
  perl: 5.8.0
resources:
  bugtracker: http://github.com/bobtfish/text-multimarkdown/issues
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/bobtfish/text-multimarkdown/
version: 1.000033
